"""Recommendations endpoint (Phase 5a / 6).

POST /api/v1/recommendations
  Body:  RecommendRequest
  200:   RecommendResponse  (even when skip_llm=True / empty list)
  422:   validation errors  (handled globally in api/errors.py)
  429:   rate limit exceeded (SlowAPI — Phase 6)
  502:   Groq quota/billing error
  503:   dataset not loaded (raised in deps.get_repository)
  504:   upstream timeout

Phase 6: rate limited to settings.rate_limit_per_minute per IP per minute.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter, Request
from slowapi import Limiter
from slowapi.util import get_remote_address

from api.deps import RepoDep, SettingsDep
from api.schemas.request import RecommendRequest
from api.schemas.response import RecommendResponse
from api.services.recommendation_service import RecommendationService
from config.settings import get_settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1", tags=["recommendations"])

# Use a module-level limiter; key function matches the one in api/main.py
_limiter = Limiter(key_func=get_remote_address)


@router.post(
    "/recommendations",
    response_model=RecommendResponse,
    summary="Get restaurant recommendations",
    description=(
        "Accepts user preferences (location, budget, cuisines, rating, free-text) "
        "and returns a ranked list of restaurant recommendations. "
        "Hard constraints are applied via a structured filter; "
        "ranking and explanations are generated by the Groq LLM. "
        "Rate limited to 30 requests per minute per IP (configurable via RATE_LIMIT_PER_MINUTE)."
    ),
    responses={
        200: {"description": "Ranked recommendations (or empty list with message if no candidates)"},
        422: {"description": "Invalid preference fields"},
        429: {"description": "Rate limit exceeded"},
        502: {"description": "Groq API quota or billing error"},
        503: {"description": "Dataset not yet loaded"},
        504: {"description": "Groq API timeout after retries"},
    },
)
@_limiter.limit(f"{get_settings().rate_limit_per_minute}/minute")
async def post_recommendations(
    request: Request,  # required by SlowAPI
    body: RecommendRequest,
    repo: RepoDep,
    settings: SettingsDep,
) -> RecommendResponse:
    service = RecommendationService(repo, settings)
    return await service.recommend(body)
